[project]
name = "setrain"
version = "0.1.0"
description = "Speech Enhancement Training"
readme = "README.md"
requires-python = "<3.10, >=3.9"
dependencies = [
    "espnet>=202511",
    "librosa>=0.11.0",
    "matplotlib>=3.9.4",
    "numpy>=1.12.1",
    "omegaconf>=1.4.1",
    "onnx>=1.19.1",
    "onnxruntime>=1.19.2",
    "p-tqdm>=1.4.2",
    "pandas>=2.3.3",
    "pesq>=0.0.4",
    "ptflops>=0.7.5",
    "pystoi>=0.4.1",
    "soundfile>=0.13.1",
    "tensorboard>=2.20.0",
    "torch>=1.2.0",
    "torchaudio>=2.8.0",
    "tqdm>=4.23.3",
]
